condense_wildcard_suffixes = true
format_code_in_doc_comments = true
match_arm_blocks = false
match_block_trailing_comma = true
imports_granularity = "Crate"
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
version = "Two"
